### ISSUE TITLE
Support of SQLAlchemy 2.0

### ISSUE THREAD

**Issue by grongierisc** [caretdev/sqlalchemy-iris#3]
Is there any reason that the engine does not support SQLAlchemy 2 ?
Especially that Pandas 2.0 is released.

**Comment by daimor** [comment]
I did not notice the release of Pandas, and did not check if it will work together, yet

**Comment by grongierisc** [comment]
SQLAlchemy 2 work with pandas 2, I haven't tried with iris-sqlalchemy yet

**Comment by daimor** [comment]
Still needs some fixes (
tests failed on 2

**Comment by daimor** [comment]
I almost made it, and then they released 2.0.11 and most of the tests do not work anymore

**Comment by daimor** [comment]
v0.9.0 on the way with the support of SQLAlchemy 2.0
