### ISSUE TITLE
%CHECKPRIV

### ISSUE THREAD

**Issue by sween** [caretdev/sqlalchemy-iris#9]
https://github.com/caretdev/sqlalchemy-iris/blob/e6430dc645bdeec9234ce688611c6cab4a4ee6c6/sqlalchemy_iris/base.py#L884

Hello, not an issue really, but a question...

Did you find that `%CHECKPRIV` was required here ?

**Comment by daimor** [comment]
Well, I implemented it there, mostly due to limited permissions on InterSystems Cloud, this check required to disable some functionalities, which was needed due to lack of functionality on the IRIS side elsewhere.

so, what's the issue?

**Comment by sween** [comment]
ah, ok, thats where I am seeing it (Cloud SQL), and thought it more a culprit than a workaround those limitations...

```
(intersystems_iris.dbapi._DBAPI.InterfaceError) [SQLCODE: <-99>:<Privilege violation>]
[Error: <<INVALID OREF>SQLPUBLICSECURITYCheck+1^%SYS.SQLSEC>]
[Location: <Prepare>]
[%msg: <User SQLAdmin is not privileged for the operation>]
```

**Comment by daimor** [comment]
probably they changed it to more restricted, before implementing it, sqlalchemy was not able to do anything there

I don't know, closing the ability to even check privileges on the server, sounds like a strange idea, how now I'm supposed to use it.

**Comment by sween** [comment]
right!

Thanks, Ill see if I can track things down @daimor , appreciate you getting back.
